style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/nd-js
options:
  commits:
    filters:
      Type:
        - feature
        - improve
        - fix
        - refactor
        - doc
        - test
  commit_groups:
    title_maps:
      feature: Features
      improve: Improving User Experience
      refactor: Code Refactoring
      fix: Fixes Bug
      doc: Documentation
      test: Testing
  header:
    pattern: "^\\[(\\w*)\\]\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  issues: 
    prefix: 
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
