style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/nd-js
options:
  commits:
    filters:
      Type:
        - feature
        - improve
        - fix
        - refactor
        - doc
        - lib
  commit_groups:
    title_maps:
      feature: 1) Features
      improve: 2) Improving User Experience
      fix: 3) Fixes Bug
      doc: 4) Documentation
      refactor: 5) Code Refactoring
      lib: 6) Libraries
  header:
    pattern: "^\\[(\\w*)\\]\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  issues: 
    prefix: 
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
